-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity obipm_support_logic is
port (
    ack_ip : OUT STD_LOGIC_VECTOR (4 downto 0);
    ack_ip_ap_vld : OUT STD_LOGIC;
    interrupt_ip : IN STD_LOGIC_VECTOR (4 downto 0);
    interrupt_cpu : OUT STD_LOGIC_VECTOR (0 downto 0);
    interrupt_cpu_ap_vld : OUT STD_LOGIC;
    interrupt_internal : IN STD_LOGIC_VECTOR (0 downto 0);
    ack_internal : IN STD_LOGIC_VECTOR (4 downto 0);
    acked : OUT STD_LOGIC_VECTOR (0 downto 0);
    acked_ap_vld : OUT STD_LOGIC;
    irq : OUT STD_LOGIC_VECTOR (0 downto 0);
    irq_ap_vld : OUT STD_LOGIC );
end;


architecture behav of obipm_support_logic is 
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";



begin



    ack_ip <= ack_internal;
    ack_ip_ap_vld <= ap_const_logic_1;
    acked <= "0" when (ack_internal = ap_const_lv5_0) else "1";
    acked_ap_vld <= ap_const_logic_1;
    interrupt_cpu <= interrupt_internal;
    interrupt_cpu_ap_vld <= ap_const_logic_1;
    irq <= "0" when (interrupt_ip = ap_const_lv5_0) else "1";
    irq_ap_vld <= ap_const_logic_1;
end behav;
