// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module obipm_interrupt_controller (
        ap_clk,
        ap_rst,
        interrupt_ip,
        transaction_r,
        irq
);

parameter    ap_ST_fsm_state2 = 2'b10;

input   ap_clk;
input   ap_rst;
input  [4:0] interrupt_ip;
input  [0:0] transaction_r;
input  [0:0] irq;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
reg   [1:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'b10;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state2;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

endmodule //obipm_interrupt_controller
